/** Conversão compartilha requisitos entre autor, fases e crítica. */
export const LANDING_COMPOSITION = `## Composição da Landing Page
Uma única home indexável (type page, slug vazio) e uma página thank_you com noindex. Posts são opcionais; não crie paid_lp nem páginas internas. A home tem pelo menos 250 palavras úteis, stage conversion e 6 a 11 seções de conteúdo, sem contar nav e footer.
Ordem: nav.bar minimal com position fixed e stickyCta true; hero.landing stage ou form; prova confirmada; narrative.statement sobre o problema; protagonista feature.bento showcase ou feature.showcase steps/tabs com duas fotos distintas; narrative.steps horizontal; depoimentos somente reais; preços somente confirmados; FAQ com 4 a 8 perguntas; cta.band band ou form.lead no fim; footer.compact minimal. Sem prova, omita a seção e registre a lacuna; o gate impedirá publicação até haver evidência.
O hero, menu, cartões de preço, CTAs do meio e fechamento apontam exatamente ao mesmo href: formulário desta home ou link externo. Repita a ação no hero, em uma seção do meio e no fechamento; o menu não conta nessa repetição. O hero pode ter um único secundário. Links do menu são âncoras existentes ou a ação principal. Não use o atalho whatsapp de cta.band; use o mesmo href rastreado em todos os botões.
Formulário tem 2 a 4 campos e redirectTo da página de obrigado. hero.landing form embute o mesmo formulário: formAnchor identifica seu destino, por padrão contato; não repita essa âncora no bloco externo. Na abertura stage, upload real do produto ou tela tem preferência. Não use foto gerada como prova de pessoa ou cliente.
Cada item de proof.strip, proof.testimonials e cada selo do hero copia em evidence uma frase exata de brief.evidence que contém o valor, rótulo, nome, cargo, citação e resultado exibidos. Use citações curtas literais; nunca acrescente uma afirmação. Em proof.stats/logos e preços, os fatos também precisam constar no briefing.
Headline até 60 caracteres, subtext até 20 palavras. Alterne paper, soft e accent/secondary, com a cor concentrada em uma faixa e ações. Uma protagonista com duas fotos é obrigatória; imageScenes contém cinco vagas na própria home. Nunca gere retratos para depoimentos. A foto de cta.band acompanha um painel de texto sólido e legível.
Conteúdo visível e utilizável no celular: controles de 48 px, formulário em coluna única, botão fixo de 56 px. Ele some com formulário visível, campo em foco, menu aberto e em telas baixas. Respeite movimento reduzido e foco por teclado. Depois de montar, a revisão é humana pela prévia; não abra Conferir nem publique.`;

export const LANDING_DESIGN = `## Direção da Landing Page
Perfil v7: omita structure e structureRationale. heroComposition stage ou form; navigation minimal. Sem referência, use os eixos e dials da vibe. Com referência visual verificada, ela modula fonte, superfície, imagens, ritmo e movimento, preservando a forma de página única e as duas composições do hero. Não escolha uma das estruturas multipágina.
Defina conceito ligado ao negócio, elemento visual recorrente, paleta legível, raio e pares tipográficos. Preserve cores editadas pelo operador. Preencha referenceDirection com as seis aplicações verificadas quando existir referência. Nunca presuma uma leitura visual a partir de texto ou URL.
brief.pagePlan tem exatamente uma entrada: slug vazio, stage conversion, intent, content e evidence. brief.goal descreve uma única ação. Cinco imageScenes: abertura hero.stage ou hero.form, duas protagonistas feature.bento, apoio media.image e fechamento cta.band, todas com page vazio. Os pedidos devem corresponder ao plano de cenas recebido.
A unicidade mede pelo menos dois eixos diferentes dentro da vibe e compara a silhueta. A estrutura de conversão pode se repetir quando direção e conteúdo são próprios.`;

export const LANDING_REVIEW = `Landing Page: use criterio conversao para ações primárias concorrentes, prova sem fato confirmado ou formulário com campos desnecessários. Verifique ordem benefício, prova, entendimento e ação na mesma home, sem pedir páginas internas. Compare os destinos e o conteúdo com o briefing. Nos pixels mobile, confira alvo de 48 px, botão fixo, formulário legível, teclado e menu aberto; não conclua sobre um estado sem evidência atual.`;
